POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "adam", "password": "Pass1234!" }

###

POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "adam", "password": "Pass1234!", "email": "adam@mail.com" }
###

GET http://127.0.0.1:8000/ping 
Content-Type: application/json
Authorization: token xxx
